package fi.vrk.xroad.fileserviceclient;

import fi.vrk.xroad.fileservice.ErrorResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-11-29T16:52:34.477+02:00
 * Generated source version: 3.1.4
 *
 */
@WebService(targetNamespace = "http://vrk.fi/xroad/fileservice", name = "XroadFileService")
@XmlSeeAlso({eu.x_road.xsd.identifiers.ObjectFactory.class})
public interface XroadFileService {

    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://vrk.fi/xroad/fileservice", className = "fi.vrk.xroad.fileservice.GetRequestType")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://vrk.fi/xroad/fileservice", className = "fi.vrk.xroad.fileservice.GetResponseType")
    @WebResult(name = "object", targetNamespace = "http://vrk.fi/xroad/fileservice")
    public javax.activation.DataHandler get(
            @WebParam(name = "name", targetNamespace = "http://vrk.fi/xroad/fileservice")
                    String name,
            @WebParam(mode = WebParam.Mode.INOUT, name = "client", targetNamespace = "http://x-road.eu/xsd/xroad" +
                    ".xsd", header = true)
                    javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadClientIdentifierType> client,
            @WebParam(mode = WebParam.Mode.INOUT, name = "service", targetNamespace = "http://x-road.eu/xsd/xroad" +
                    ".xsd", header = true)
                    javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadServiceIdentifierType> service,
            @WebParam(mode = WebParam.Mode.INOUT, name = "userId", targetNamespace = "http://x-road.eu/xsd/xroad" +
                    ".xsd", header = true)
                    javax.xml.ws.Holder<String> userId,
            @WebParam(mode = WebParam.Mode.INOUT, name = "id", targetNamespace = "http://x-road.eu/xsd/xroad.xsd",
                    header = true)
                    javax.xml.ws.Holder<String> id,
            @WebParam(mode = WebParam.Mode.INOUT, name = "protocolVersion", targetNamespace = "http://x-road.eu/xsd/xroad.xsd", header = true)
                    javax.xml.ws.Holder<String> protocolVersion
    ) throws ErrorResponse;
}
