
package fi.vrk.xroad.fileservice;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-17T12:52:41.101+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "errorResponse", targetNamespace = "http://vrk.fi/xroad/fileservice")
public class ErrorResponse extends Exception {

    private ErrorResponseType errorResponse;

    public ErrorResponse() {
        super();
    }

    public ErrorResponse(String message) {
        this(message, new ErrorResponseType());
    }

    public ErrorResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ErrorResponse(String message, ErrorResponseType errorResponse) {
        super(message);
        this.errorResponse = errorResponse;
    }

    public ErrorResponse(String message, ErrorResponseType errorResponse, Throwable cause) {
        super(message, cause);
        this.errorResponse = errorResponse;
    }

    public ErrorResponseType getFaultInfo() {
        return this.errorResponse;
    }
}
